# Generated by Django 3.2.8 on 2022-09-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Lname',
            new_name='Sub',
        ),
    ]
