# Generated by Django 3.2.8 on 2022-09-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_lname_contact_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Fname',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Msg',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Sub',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
